### ISSUE TITLE
GraphQL error if Tx has inputData

### ISSUE THREAD

**Issue by SavonarolaBit** [nautls/nautilus-wallet#105]
Sending a transaction with inputData through Nautilus Testnet 0.8.2 produces the following error:
```
{code: -2, info: '[GraphQL] ERGO_NODE_ADDRESS is undefined in .env file.'}
```

Minimal example repo: https://github.com/SavonarolaBit/bug-tx-inputData

1-liner to reproduce: 
```
git clone git@github.com:SavonarolaBit/bug-tx-inputData.git && cd bug-tx-inputData && npm i && npm run dev -- --open
```

**Comment by capt-nemo429** [comment]
Hi, thank you for you detailed report, this is happening because, unfortunately, official testnet GraphQL instance is misconfigured for a long time ago. 

To solve that you can go to **Settings** and replace the current **GraphQL Server** by some alternative instance like `https://tn-ergo-explorer.anetabtc.io/graphql`
